config/routes.rb
Plazr::Application.routes.draw do

  mount PlazrAuth::Engine => '/'

  resources :plazrrs
  resources :payment_methods
  resources :stores

  namespace :root do
    resources :users
    resources :store_categories
    match "users/:user_id/addrole" => "users#addrole" , :via => :get ,:as => :add_role
    match "users/:user_id/:role_id/rmrole" => "users#rmrole" , :via => :get ,:as => :rem_role
  end

  get 'pages/prices' => 'pages#prices'
  get 'pages/terms' => 'pages#terms'
  get 'pages/index' => 'pages#index'
  get 'pages/about' => 'pages#about'

  root to: 'pages#index'

end

app/models/payment_method.rb
class PaymentMethod < ActiveRecord::Base
  attr_accessible :title, :description
  
end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  def index
    @payment_methods = PaymentMethod.all
  end
  def new
    @payment_method = PaymentMethod.new
  end
  def create
    @payment_method = PaymentMethod.new(params[:payment_method])
    @payment_method.save
    redirect_to payment_methods_path
  end
  def show
    @payment_method = PaymentMethod.find(params[:id])
  end
  def edit
    @payment_method = PaymentMethod.find(params[:id])
  end
  def update
    @payment_method = PaymentMethod.find(params[:id])
    @payment_method.update_attributes(params[:payment_method])
    redirect_to(payment_method_path(@payment_method))
  end
  def destroy
    @payment_method = PaymentMethod.find(params[:id])
    @payment_method.destroy
    redirect_to(payment_methods_path)
  end
end

app/helpers/payment_methods_helper.rb
module PaymentMethodsHelper
end

app/views/payment_methods/edit.html.erb
<h1>Edit Payment Method</h1>

<%= form_for(@payment_method) do |f| %>
	<ul>
	<% @payment_method.errors.full_messages.each do |error| %>
		<li><%= error %></li>
	<% end %>
	</ul>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :description %><br>
		<%= f.text_field :description %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/payment_methods/index.html.erb
<h1>All Payment Methods</h1>

<ul>
  <% @payment_methods.each do |method| %>
    <li>
      <%= link_to method.title, payment_method_path(method) %>
    </li>
  <% end %>
</ul>

<%= link_to "Create new Payment Method", new_payment_method_path %><br>
<%= link_to "Back To Home", plazrrs_path %>

app/views/payment_methods/new.html.erb
<h1>Register Payment Method</h1>

<%= form_for(@payment_method) do |f| %>
	<ul>
	<% @payment_method.errors.full_messages.each do |error| %>
		<li><%= error %></li>
	<% end %>
	</ul>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :description %><br>
		<%= f.text_field :description %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/payment_methods/show.html.erb
<h1><%= @payment_method.title %></h1>
Description: <%= @payment_method.description %><br>

<p>
	<%= link_to "Edit", edit_payment_method_path(@payment_method) %>
	<%= link_to "Delete", payment_method_path(@payment_method), method: :delete %>
</p>

<%= link_to "Back Payments Index ", payment_methods_path %>