config/routes.rb
Plazr::Application.routes.draw do

  mount PlazrAuth::Engine => '/'

  resources :plazrrs
  resources :payment_methods
  resources :stores

  namespace :root do
    resources :users
    resources :store_categories
    match "users/:user_id/addrole" => "users#addrole" , :via => :get ,:as => :add_role
    match "users/:user_id/:role_id/rmrole" => "users#rmrole" , :via => :get ,:as => :rem_role
  end

  get 'pages/prices' => 'pages#prices'
  get 'pages/terms' => 'pages#terms'
  get 'pages/index' => 'pages#index'
  get 'pages/about' => 'pages#about'

  root to: 'pages#index'

end

app/models/store.rb
class Store < ActiveRecord::Base
  attr_accessible :name, :description, :email, :phone, :url, :categorizes_attributes, :postal_code, :city, :adress, :logo, :banner,
                  :latitude, :longitude, :categorizes_attributes, :store_category


  validates :name, :presence => { :message => "Nome da Loja e um campo obrigatorio." }
  validates :email, :presence => { :message => "Email da Loja e um campo obrigatorio." }
  # validates_format_of :email,
  # 					  :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
  # 					  :message => "O Email da Loja inserido esta invalido."
  # validates_format_of :url,
  #                     :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$/ix,
  #                     :allow_nil => true,
  #                     :allow_blank => true,
  # 					          :message => "O URL inserido esta invalido."
  validates_format_of :phone,
      			          :numericality => true,
      			          :length => { :minimum => 9, :maximum => 15 },
      			          :with => /\A[0-9]{9}\Z/,
      			          :allow_nil => true,
      			          :allow_blank => true,
      			          :message => "O numero de Telefone da Loja inserido esta invalido."
  validates_numericality_of :latitude, :less_than => 1000000,
                            :allow_nil => true,
                            :allow_blank => true,
                            :message => "O valor da latitude inserido esta invalido."
  validates_numericality_of :longitude, :less_than => 1000000,
                            :allow_nil => true,
                            :allow_blank => true,
                            :message => "O valor da longitude inserido esta invalido."

  has_many :categorizes
  has_many :store_categories, through: :categorizes

  def gmaps4rails_address
  #describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
    "#{self.street}, #{self.city}, #{self.country}"
  end

  accepts_nested_attributes_for :categorizes, :allow_destroy => true
  accepts_nested_attributes_for :store_categories, :allow_destroy => true

  has_attached_file :banner, :styles => { :small => "x70>" },
                  :url  => "/assets/stores/:id/banner.:extension",
                  :path => ":rails_root/public/assets/stores/:id/banner.:extension"

  validates_attachment_size :banner, :less_than => 5.megabytes
  validates_attachment_content_type :banner, :content_type => ['image/jpeg', 'image/png']

  has_attached_file :logo, :styles => { :small => "x70>" },
                  :url  => "/assets/stores/:id/logo.:extension",
                  :path => ":rails_root/public/assets/stores/:id/logo.:extension"

  validates_attachment_size :logo, :less_than => 5.megabytes
  validates_attachment_content_type :logo, :content_type => ['image/jpeg', 'image/png']

  after_save :copy_banner
  after_save :copy_logo

  def copy_logo
    if self.logo.to_s.include?("/logos/original/missing.png")
      system("mkdir -p ../plazr_stores/#{id}_#{name.to_s.parameterize}/config")
      system("echo 'logo_path: public/logo.png' >> ../plazr_stores/#{id}_#{name.to_s.parameterize}/config/config.yml")
    else
      system("mkdir -p ../plazr_stores/#{id}_#{name.to_s.parameterize}/public/assets/upload/logo/logo")
      system("cp #{logo.path} ../plazr_stores/#{id}_#{name.to_s.parameterize}/public/assets/upload/logo/logo")

      system("mkdir ../plazr_stores/#{id}_#{name.to_s.parameterize}/config")
      system("echo 'logo_path: public/assets/upload/logo/logo/#{File.basename(logo.path)}' >> ../plazr_stores/#{id}_#{name.to_s.parameterize}/config/config.yml")
    end
  end

  def copy_banner
    if self.banner.to_s.include?("/banners/original/missing.png")
      system("mkdir -p ../plazr_stores/#{id}_#{name.to_s.parameterize}/config")
      system("echo 'banner_path: public/banner.jpg' >> ../plazr_stores/#{id}_#{name.to_s.parameterize}/config/config.yml")
    else
      system("mkdir -p ../plazr_stores/#{id}_#{name.to_s.parameterize}/public/assets/upload/banner/banner")
      system("cp #{banner.path} ../plazr_stores/#{id}_#{name.to_s.parameterize}/public/assets/upload/banner/banner")

      system("mkdir ../plazr_stores/#{id}_#{name.to_s.parameterize}/config")
      system("echo 'banner_path: public/assets/upload/banner/banner/#{File.basename(banner.path)}' >> ../plazr_stores/#{id}_#{name.to_s.parameterize}/config/config.yml")
    end
  end


  def get_unselected_categories
    # creates an array for all property_prototypes that the prototype does not currently have selected
    # and builds them in the prototype
    (StoreCategory.all - self.store_categories).each do |p|
      self.categorizes.build(:store_category_id => p.id) unless self.categorizes.map(&:store_category_id).include?(p.id)
    end
    # to ensure that all properties are always shown in a consistent order
    self.categorizes.sort_by! {|x| x.store_category.title}
  end
end

app/controllers/stores_controller.rb
  class StoresController < ApplicationController

  before_filter :check_admin, only: [:new, :edit, :destroy]


  def index

    @store_categories = StoreCategory.where("parent IS NOT ?",nil)

    if params[:search] && params[:search]!='All'

      @stores = []

      Store.all.each do |s|
        if(s.store_categories.exists?(params[:search]))
          @stores.push(s)
        end
      end

    else
      if params[:keyword] && !params[:keyword].blank?
        @stores = []

        Store.all.each do |s|
          if( s.name.upcase.include?(params[:keyword].upcase) ||
              s.description.upcase.include?(params[:keyword].upcase) ||
              s.url.upcase.include?(params[:keyword].upcase)
              )
            @stores.push(s)
          end
        end
      else
        @stores = Store.all
      end
    end

  end
  def new
    # @json =Store.all.to_gmaps4rails
    @store=Store.new
    @store.get_unselected_categories
  end


  def create
    # @json = Store.all.to_gmaps4rails
    @store= Store.new(params[:store])
    # @store = Store.new
    # @categorize = @store.categorizes.build
    respond_to do |format|
    if @store.save

      ## script local
      system('sh ../shared/create_store_local.sh '+@store.name.to_s.parameterize+' '+@store.id.to_s)
      ## script global
      #system('sh ../shared/create_store.sh '+@store.name.to_s.parameterize+' '+@store.id.to_s)

  	  #unless current_user.roles.detect { |role| role.name == 'admin' }
      #	current_user.roles << PlazrAuth::Role.find_by_name('admin')
      #end

	  new_role = PlazrAuth::Role.create name: "admin_#{@store.id}"
	  current_user.roles << new_role

      format.html {
        # redirect_to store_path (@store), :notice => 'Store was successfully created.'
        port = 3000 + @store.id
        redirect_to 'http://ouassim.dyndns.org:'+port.to_s
      }

      format.html { redirect_to(@store, :notice => 'A sua loja foi criada com sucesso.') }
    else
      @store.get_unselected_categories
      format.html { render :action => "new" }
    end



  end

  end
  def edit
    @store = Store.find(params[:id])
    @store.get_unselected_categories
  end
  def destroy
    @store = Store.find(params[:id])
    system("kill -9 `lsof -wni tcp:30"+@store.id.to_s+" | grep ruby | awk '{ print  $2 }'`")
    system("rm -rf ../plazr_stores/"+@store.id.to_s+"_"+@store.name.to_s.parameterize)
    @store.destroy

    redirect_to stores_path
  end
  def show
    @store = Store.find(params[:id])
  end
  def update
    #raise params.inspect
    @store = Store.find(params[:id])
    @store.update_attributes(params[:store])
    redirect_to store_path(@store)
  end


  protected

    def check_admin
      unless can? :create, :store
        flash[:error] = 'You don\'t have permission to access this'
        redirect_to root_path
      end
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_categorize_fields.html.erb
<div class='nested-fields'>
	<%= f.association :store_category, :collection => StoreCategory.where("parent IS NOT ?",nil), :prompt => 'Escolhe uma Categoria' %>
	<%= link_to_remove_association "Remover", f %><br>
</div>

app/views/stores/_form.html.erb
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<head>
	<script type="text/javascript">
	var geocoder;
	var map;
	var oldMarker;
	
<<<<<<< HEAD
	function initialize() {
		geocoder = new google.maps.Geocoder();
		var latlng = new google.maps.LatLng(39.5, -8.3);
		var myOptions = {
			center: latlng,
			zoom: 6,
			mapTypeId: google.maps.MapTypeId.HYBRID,
			streetViewControl: false
		}
		map = new google.maps.Map(document.getElementById("mapa"), myOptions);
		placeMarker(latlng, 0);
	}
=======
	<%= f.label :name, "Title" %>
	<%= f.text_field :name %><br>
	<%= f.label :description, "Description" %>
	<%= f.text_field :description %><br>
	<%= f.label :email, "Email" %>
	<%= f.text_field :email %><br>
	<%= f.label :phone, "Phone" %>
	<%= f.text_field :phone %><br>
	<%= f.label :url, "URL" %>
	<%= f.text_field :url %><br>

	<%= f.label :adress, "Adress" %>
	<%= f.text_field :adress %><br>

	<%= f.label :postal_code, "Postal Code" %>
	<%= f.text_field :postal_code %><br>

	<%= f.label :city, "City" %>
	<%= f.text_field :city %><br><br>

  <%= f.label :logo %>
	<%= f.file_field :logo %><br>

  <%= f.label :banner %>
	<%= f.file_field :banner %><br>

  <h3>Categories</h3>
  <div id='tasks'>
    <%= f.simple_fields_for :categorizes do |task| %>
      <%= render 'categorize_fields', :f => task %>
  	<% end %>
    <%= link_to_add_association 'Add Category', f, :categorizes %><br>
	</div>
  <p>
  	<%= f.submit 'Save Store' %>
  </p>
>>>>>>> 60f37d18b967218f66fc0927f8c77d699a8ceb61

	function placeMarker(location, first) {

		var marker = new google.maps.Marker({
			position: location,
			map: map,
			animation: google.maps.Animation.DROP,
			draggable: true
		});

		if(first != 0){
			map.setZoom(16);
		}
		if (oldMarker != undefined){
			oldMarker.setMap(null);
		}
		oldMarker = marker;

		map.setCenter(location);

		document.getElementById("store_latitude").value = event.location.lat();
		document.getElementById("store_longitude").value = event.location.lng();

		var iw = new google.maps.InfoWindow({
			content: "A sua loja fica aqui!!!"
		});
		google.maps.event.addListener(marker, "click", function (e) { iw.open(map, marker); });

		google.maps.event.addListener(marker, 'drag', function(event){
			document.getElementById("store_latitude").value = event.latLng.lat();
			document.getElementById("store_longitude").value = event.latLng.lng();
		});
		google.maps.event.addListener(marker, 'click', toggleBounce);

	}

	function toggleBounce() {

		if (marker.getAnimation() != null) {
			marker.setAnimation(null);
		} else {
			marker.setAnimation(google.maps.Animation.BOUNCE);
		}
	}

	function codeAddress() {
		var address = document.getElementById("address").value;
		var city = document.getElementById("city").value;
		var codP1 =  document.getElementById("codP1").value; 
		var codP2 =  document.getElementById("codP2").value; 
		var location = address + ", " + city + ", " + codP1 + "-" + codP2;
		geocoder.geocode( { 'address': location}, function(results, status) {
			if (status == google.maps.GeocoderStatus.OK) {
				placeMarker(results[0].geometry.location, 1);
			} else {
				alert("A localização da sua loja não foi bem sucedida. Certifique-se que escreveu a morada corretamente.");
			}
		});
	}

	function codeLatLng() {
		var lat = parseFloat(document.getElementById("store_latitude").value);
		var lng = parseFloat(document.getElementById("store_longitude").value);
		var latlng = new google.maps.LatLng(lat, lng);
		geocoder.geocode({'latLng': latlng}, function(results, status) {
			if (status == google.maps.GeocoderStatus.OK) {
				if (results[1]) {
					placeMarker(latlng, 1);
				}
			} else {
				alert("A localização da sua loja não foi bem sucedida. Certifique-se que escreveu corretamente  a Latitude e Longitude.");
			}
		});
	}

	</script>
</head>
<body onload="initialize()">

	<h1><span>Nova Loja</span></h1>
	<%= simple_form_for @store do |f| %>
	<div class="wrap announcement-container"  id="etapa1" style="padding-top: 16.5px; padding-bottom: 16.5px;">
		<%= render "shared/error_messages", :target => @store %>
		<div class="row-fluid">
			<div class="span12">
				<h2><span class="logo">Dados da Loja</span></h2>
			</div>
		</div>
		<table>
			<tr>
				<th align="right"><%= f.label :name, "Nome da Loja:" %></th>
				<th align="left"><%= f.text_field :name, :required => true, :placeholder => "Plazr" %></th>
			</tr>
			<tr>
				<th align="right"><%= f.label :description, "Descrição:" %></th>
				<th align="left"><%= f.text_area :description , :cols => 29, :rows => 2, :required => false, :placeholder => "O Plazr permite criar uma loja online" %></th>
			</tr>
			<tr>
				<th align="right"><%= f.label :email, "Email da Loja:" %></th>
				<th align="left"><%= f.text_field :email, :required => true, :placeholder => "plazr@example.com" %></th>
			</tr>
			<tr>
				<th align="right"><%= f.label :phone, "Telefone da Loja:" %></th>
				<th align="left"><%= f.text_field :phone, :required => false, :required => false, :placeholder => "911111111"%></th>
			</tr>
			<tr>
				<th align="right"><%= f.label :url, "URL Pretendido:" %></th>
				<th align="left"><%= f.url_field :url, :placeholder => "http://www.plazr.net" %></th>
			</tr>
			<tr>
				<th align="right"><%= f.label :url, "Localização:" %></th>
				<th align="left">
					<% gmaps4rails(@json) %>
					<div>
						<p>Morada<input id="address" type="textbox" placeholder ="Rua da Alegria, 26, Lordelo" /></p>
						<p>Cidade<input id="city" type="textbox" placeholder="Guimarães" /></p>
						<p>Código Postal<input id="codP1" type="number" maxlength= 4 placeholder="4815" />-<input id="codP2" type="number" maxlength= 3 placeholder="144" /></p>
						<input type="button" value="Localizar no mapa" onclick="codeAddress()" />
					</div>
					<div id="mapa" style="width:600px; height:320px"></div>
					<div id="latlong">
						<p>Latitude: <%= f.text_field :latitude, :placeholder => "39.5" %></p>
						<p>Longitude: <%= f.text_field :longitude, :placeholder => "-8.3" %></p>
					</p>
				</div>
				<p><input type="button" value="Localizar no mapa" onclick="codeLatLng()" /></p>

			</th>
		</tr>
		<th align="right">Categorias:</th>
		<th align="left">
			<div id='tasks'>
				<%= f.simple_fields_for :categorizes do |task| %>
				<%= render 'categorize_fields', :f => task %>
				<% end %>
				<%= link_to_add_association 'Adicionar Categoria', f, :categorizes %>
			</div>
		</th>
	</tr>
	<tr>
		<th><%= f.submit%></th>
	</tr>
</table>
<% end %>
</div>
<footer>
	<%= yield :scripts %>
</footer>
</body></html>

app/views/stores/edit.html.erb
<%= render 'form' %>

app/views/stores/index.html.erb
<div id="stores">
	<div class="container">
		<div class="row-fluid page-header">
			<h2>As nossas lojas</h2>
		</div>

		<div class="row-fluid">
			<div class="categories">
				<%= form_tag stores_path, :method => 'get' do %>
				<%= select_tag "search", options_for_select(["Todas"]+@store_categories.map{|a| [a.title,a.id]},params[:search]),{:onchange => 'this.form.submit()'}%>
				<% end %>
			</div>
			<div class="input-append keywords">
				<%= form_tag stores_path, :method => 'get' do %>
				<%= text_field_tag :keyword, params[:keyword], id: 'appendedInputButton' %>
				<%= submit_tag 'Pesquisar', class: 'btn' %>
				<% end %>
			</div>
		</div>

		<div class="row-fluid">
			<% if @stores.count > 0 %>
			<table class="table">
				<% @stores.each do |store| %>
				<tr>
					<td><%= link_to store.name, store_path(store) %></td>
					<% store_url = 3000 + store.id%>
					<td><%= link_to "View Store >>", "http://localhost:" + store_url.to_s + "/" %></td>
				</tr>
				<% end %>
			</table>
			<% else %>
			<p>Não existem lojas!</p>
			<% end %>
		</div>
		<div class="row-fluid buttons">
			<%= link_to "Criar Nova Loja",  new_store_path %>
			<%= link_to "Voltar para a Página Principal",  plazrrs_path %>
		</div>
	</div>
</div>

app/views/stores/new.html.erb
<% content_for :javascript_includes do %>
	<%= javascript_include_tag :new_store %>
	<%= javascript_include_tag :maps %>
<% end %>

<div class="progress-wrap">
	<div class="container">
		<div class="progress">
			<div class="bar">
			</div>
		</div>
	</div>
</div>

<%= form_for(@store, html: {class: 'form-horizontal'}) do |f| %>

<section id="section-one">
	<div class="container">
		<header>
			<h1>Bem-Vindo ao Plazr!</h1>
			<p>Utilize o Plazr para criar a sua loja online!<br />Deve preencher o formulário das próximas três etapas para concluir o prcesso de criar a sua loja!</p>
		</header>
		<section>
			<div class="input-append">
				<label>Indique que nome pretende dar à sua loja: </label>
				<%= f.text_field :name, :required => true, :placeholder => "Plazr", class: 'input-xxlarge span3' %>
				<a href="#sectionTwo" class="btn btn-primary">Continuar</a>
			</div>
		</section>
	</div>
</section>

<section id="section-two">
	<div class="container">
		<header>
			<h2>Informação Básica</h2>
			<p>Deve indificar uma descrição para a loja e associa-la a uma ou mais categorias.</p>
		</header>
		<section>
			<div class="control-group">
				<label class="control-label">
					Descrição da loja:
				</label>
				<div class="controls">
					<%= f.text_field :description, :rows => 2, :required => false, :placeholder => "O Plazr permite criar uma loja online.", class: 'input-xxlarge' %>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label">
					Categorias:
				</label>
				<div class="controls">
					<ul class="checklistbox input-xxlarge">
						<%= f.fields_for :categorizes do |ff| %>
							<li>
								<div class="checkbox">
									<%= ff.check_box :_destroy, {:checked => ff.object.persisted?}, '0', '1' %>
									<%= ff.object.store_category.title unless ff.object.store_category.nil? %>
								</div>
								<%#= ff.label :_destroy, ff.object.store_category.title %>
								<%= ff.hidden_field :store_category_id %>
							</li>
						<% end %>
					</ul>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label">
					<%= f.label :url, "URL Pretendido:" %>
				</label>
				<div class="controls">
					<%= f.text_field :url, :placeholder => "http://www.plazr.net", class: 'input-xxlarge' %>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label">Logo:</label>
				<div class="controls logo">
					<%= f.file_field :logo %>
				</div>
			</div>
			<div class="pull-right buttons-top">
				<a href="#sectionOne" class="btn btn-primary">Anterior</a>
				<a href="#sectionThree" class="btn btn-primary">Continuar</a>
			</div>
			<div class="clearfix"></div>
		</section>
	</div>
</section>

<section id="section-three">
	<div class="container">
		<header>
			<h2>Contactos</h2>
			<p>Deve indicar os contactos da loja!</p>
		</header>
		<section>
			<div class="control-group">
				<label class="control-label">
					<%= f.label :email, "Email da loja:" %>
				</label>
				<div class="controls">
					<%= f.text_field :email, :required => true, :placeholder => "plazr@example.com", class: 'input-xxlarge' %>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label">
					<%= f.label :phone, "Telefone da Loja:" %>
				</label>
				<div class="controls">
					<%= f.text_field :phone, :required => false, :required => false, :placeholder => "911111111", class: 'input-xxlarge' %>
				</div>
			</div>
			<div class="pull-right buttons-top">
				<a href="#sectionTwo" class="btn btn-primary">Anterior</a>
				<a href="#sectionFour" class="btn btn-primary">Continuar</a>
			</div>
			<div class="clearfix"></div>
		</section>
	</div>
</section>

<section id="section-four">
	<div class="container">
		<header>
			<h2>Localização</h2>
			<p>Indique a morada da sua loja!</p>
		</header>
		<section>
			<table class="pull-left">
				<tr>
					<td>Morada</td>
					<td><%= f.text_field :adress, placeholder: "Rua da Alegria, 26, Lordelo", id: "address" %></td>
				</tr>
				<tr>
					<td>Cidade</td>
					<td><%= f.text_field :city, placeholder: "Guimarães", id: "city"	 %></td>
				</tr>
				<tr>
					<td>Cod Postal</td>
					<td><%= f.text_field :postal_code, placeholder: "1234-567", id: 'codP' %></td>
				</tr>
				<tr>
					<td>
						<input type="button" id="updated_map" value="Actualizar mapa" class="btn btn-info" />
					</td>
				</tr>
			</table>

<!-- 			<div class="location">
				<% gmaps4rails(@json) %>
			</div>
		-->
		<div class="pull-right">
			<div class="pull-right buttons">
				<a href="#sectionThree" class="btn btn-primary">Anterior</a>
				<a href="#sectionFive" class="btn btn-primary">Continuar</a>
			</div>
			<div class="clearfix"></div>
			<div id="mapa" class="" style="width:600px; height:280px"></div>
		</div>
		<div class="clearfix"></div>
	</section>
</div>
</section>

<section id="section-five">
	<div class="container">
		<header>
			<h2>Concluído</h2>
			<p>Muito obrigado! Por favor carregue em submeter para terminar.</p>
		</header>
		<section>
			<p>Confirme por favor antes de submeter!</p>
			<dl class="dl-horizontal">
				<dt>Nome:</dt>
				<dd><span class="name"></span></dd>
				<dt>Email:</dt>
				<dd><span class="email"></span></dd>
				<dt>Telefone:</dt>
				<dd><span class="tel"></span></dd>
			</dl>
			<div class="pull-right buttons-top">
				<a href="#sectionFour" class="btn btn-primary">Anterior</a>
				<%= f.submit 'Submeter', class: 'btn btn-primary' %>
			</div>
			<div class="clearfix">
			</div>
		</section>
	</div>
</section>

<% end %>

app/views/stores/old_form.html.erb
<h1>New Store</h1>

<%= simple_form_for @store, :html => { :multipart => true } do |f| %>
	<%= render "shared/error_messages", :target => @store %>
	
	<%= f.label :name, "Title" %>
	<%= f.text_field :name %><br>
	<%= f.label :description, "Description" %>
	<%= f.text_field :description %><br>
	<%= f.label :email, "Email" %>
	<%= f.text_field :email %><br>
	<%= f.label :phone, "Phone" %>
	<%= f.text_field :phone %><br>
	<%= f.label :url, "URL" %>
	<%= f.text_field :url %><br>

	<%= f.label :adress, "Adress" %>
	<%= f.text_field :adress %><br>

	<%= f.label :postal_code, "Postal Code" %>
	<%= f.text_field :postal_code %><br>

	<%= f.label :city, "City" %>
	<%= f.text_field :city %><br><br>

	<%= f.file_field :logo %><br>
	<%= f.file_field :banner %>

  <h3>Categories</h3>
  <div id='tasks'>
    <%= f.simple_fields_for :categorizes do |task| %>
      <%= render 'categorize_fields', :f => task %>
  	<% end %>
    <%= link_to_add_association 'Add Category', f, :categorizes %><br>
	</div>
  <p>
  	<%= f.submit 'Save Store' %>
  </p>

<% end %>

app/views/stores/old_index.html.erb
<h1>Stores </h1>

<% if @stores.count > 0 %>
	<ul>
		<% @stores.each do |store| %>
			<li>
				<%= link_to store.name, store_path(store) %>
			</li>
		<% end %>
	</ul>
<% else %>
	No Stores Available 
<% end %>

<p>
	<%= link_to "Create Your Store",  new_store_path %><br>
	<%= link_to "Back to Home",  plazrrs_path %>
</p>

app/views/stores/old_show.html.erb
<h1><%= @store.name %></h1>
Name: <%= @store.name %><br>
Description: <%= @store.description %><br>
Email: <%= @store.email %><br>
Phone: <%= @store.phone %><br>
URL: <%= @store.url %><br>
<p>
	Categories:<br>
	<% @store.store_categories.each do |c| %>
		<%= link_to c.title, store_category_path(c) %>
	<% end %>
</p>	

<p>
	<%= link_to "Edit Store", edit_store_path(@store) %>
	<%= link_to "Delete Store", store_path(@store), method: :delete %>
</p>


<%= link_to "Back to Stores", stores_path %>

app/views/stores/show.html.erb
<h1><%= @store.name %></h1>
Name: <%= @store.name %><br>
Description: <%= @store.description %><br>
Email: <%= @store.email %><br>
Phone: <%= @store.phone %><br>
URL: <%= @store.url %><br>
Latitude: <%= @store.latitude %><br>
Longitude: <%= @store.longitude %><br>
<p>
	Categories:<br>
	<% @store.store_categories.each do |c| %>
		<%= link_to c.title, root_store_category_path(c) %>
	<% end %>
</p>	

<p>
	<%= link_to "Editar Loja", edit_store_path(@store) %>
	<%= link_to "Eliminar Loja", store_path(@store), method: :delete, data: { confirm: 'Tem a certeza?' } %>
</p>


<%= link_to "Voltar para as Lojas", stores_path %>