config/routes.rb
Plazr::Application.routes.draw do

  mount PlazrAuth::Engine => '/'

  resources :plazrrs
  resources :payment_methods
  resources :stores

  namespace :root do
    resources :users
    resources :store_categories
    match "users/:user_id/addrole" => "users#addrole" , :via => :get ,:as => :add_role
    match "users/:user_id/:role_id/rmrole" => "users#rmrole" , :via => :get ,:as => :rem_role
  end

  get 'pages/prices' => 'pages#prices'
  get 'pages/terms' => 'pages#terms'
  get 'pages/index' => 'pages#index'
  get 'pages/about' => 'pages#about'

  root to: 'pages#index'

end

app/models/store_category.rb
class StoreCategory < ActiveRecord::Base
  attr_accessible :title, :description, :parent
  
  has_many :categorizes
  has_many :stores, through: :categorizes
  
  accepts_nested_attributes_for :stores, :allow_destroy => false

end

app/controllers/root/application_controller.rb
class Root::ApplicationController < ApplicationController
  protect_from_forgery

  before_filter :check_root

  protected

    def check_root
      unless can? :admin, :plazr
        flash[:error] = 'You don\'t have permission to access this'
        redirect_to root_path
      end
    end
end

app/controllers/root/store_categories_controller.rb
class Root::StoreCategoriesController < Root::ApplicationController
  def index
    @categories  = StoreCategory.all
  end    
  def new
    @category = StoreCategory.new
  end
  def create
    @category = StoreCategory.new(params[:store_category])
    @category.save
    redirect_to(root_store_categories_path)
  end
  def show
    #@categories  = StoreCategory.all
    @category = StoreCategory.find(params[:id])
    @subcategories = StoreCategory.where(:parent => @category.id)
  end
  def edit
    @category = StoreCategory.find(params[:id])
  end
  def update
    @category = StoreCategory.find(params[:id])
    @category.update_attributes(params[:store_category])
    redirect_to(root_store_category_path(@category))
  end
  def destroy
    @category = StoreCategory.find(params[:id])
    @category.destroy
    redirect_to(root_store_categories_path)
  end
end

app/controllers/root/users_controller.rb
class Root::UsersController < Root::ApplicationController
  
  def index
    @users = PlazrAuth::User.all
  end

  def show
    @user = PlazrAuth::User.find(params[:id])
    @roles = PlazrAuth::Role.all - @user.roles
  end

  def edit
    @user = PlazrAuth::User.find(params[:id])
  end

  def update
    @user = PlazrAuth::User.find(params[:id])
    @user.update_attributes(params[:user])
    redirect_to(root_user_path(@user))
  end

  def destroy
    @user = PlazrAuth::User.find(params[:id])
    @user.destroy
    redirect_to root_users_path
  end

  def addrole
    @user = PlazrAuth::User.find(params[:user_id])
    @role = PlazrAuth::Role.find(params[:role_id])
    @user.roles.push(@role) if (@user && @role)
    redirect_to(root_user_path(@user))
  end

  def rmrole
    @user = PlazrAuth::User.find(params[:user_id])
    @role = PlazrAuth::Role.find(params[:role_id])
    @user.roles.delete(@role) if (@user && @role)
    redirect_to(root_user_path(@user))
  end

end

app/views/root/store_categories/edit.html.erb
<h1>Edit Store Category</h1>

<%= form_for [:root,@category] do |f| %>
	<ul>
	<% @category.errors.full_messages.each do |error| %>
		<li><%= error %></li>
	<% end %>
	</ul>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :description %><br>
		<%= f.text_field :description %>

	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/root/store_categories/index.html.erb
<h1>All Store Categories</h1>

<ul>
  <% @categories.each do |category| %>
    <% if (category.parent==nil) %>
    <li>
      <%= link_to category.title, root_store_category_path(category) %>
      
    </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "Create new Store Category", new_root_store_category_path %><br>
<%= link_to "Back To Home", plazrrs_path %>

app/views/root/store_categories/new.html.erb
<% if(params[:parent]) %>
	<h1>Create Store Sub-Category</h1>
<% else %>
	<h1>Create Store Category</h1>
<% end %>

<%= form_for [:root,@category] do |f| %>
	<ul>
	<% @category.errors.full_messages.each do |error| %>
		<li><%= error %></li>
	<% end %>
	</ul>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :description %><br>
		<%= f.text_field :description %>
	</p>
		<%= f.hidden_field :parent, :value => params[:parent] if params[:parent] %>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/root/store_categories/show.html.erb
<h1>Category: <%= @category.title %></h1>
  
  Description: <%= @category.description %><br>

<p>
	<%= link_to "Edit", edit_root_store_category_path(@category) %>
	<%= link_to "Delete", root_store_category_path(@category), method: :delete, data: { confirm: 'Are you sure?' } if (@subcategories.count==0) %>
</p>

<% if(@category.parent.nil?)%>
  <h2>Subcategories</h2>

  <ul>
  <% @subcategories.each do |c| %>
    
      <li>
      		<%= link_to c.title, root_store_category_path(c) %>
    	</li>
    
  <% end %>
  </ul>


<%= link_to "Add Subcategory", new_root_store_category_path(:parent => @category.id) %>
<%else%>


<h2>Stores for this Category</h2>

<ul>
  	<% @category.stores.each do |store| %>
    	<li><%= link_to store.name, root_store_path(store) %></li>
  	<% end %>
</ul>

<% end %>
<br><br>
<%= link_to "Back to Store Categories", root_store_categories_path %>