config/routes.rb
Plazr::Application.routes.draw do

  mount PlazrAuth::Engine => '/'

  resources :plazrrs
  resources :payment_methods
  resources :stores

  namespace :root do
    resources :users
    resources :store_categories
    match "users/:user_id/addrole" => "users#addrole" , :via => :get ,:as => :add_role
    match "users/:user_id/:role_id/rmrole" => "users#rmrole" , :via => :get ,:as => :rem_role
  end

  get 'pages/prices' => 'pages#prices'
  get 'pages/terms' => 'pages#terms'
  get 'pages/index' => 'pages#index'
  get 'pages/about' => 'pages#about'

  root to: 'pages#index'

end

app/controllers/root/application_controller.rb
class Root::ApplicationController < ApplicationController
  protect_from_forgery

  before_filter :check_root

  protected

    def check_root
      unless can? :admin, :plazr
        flash[:error] = 'You don\'t have permission to access this'
        redirect_to root_path
      end
    end
end

app/controllers/root/store_categories_controller.rb
class Root::StoreCategoriesController < Root::ApplicationController
  def index
    @categories  = StoreCategory.all
  end    
  def new
    @category = StoreCategory.new
  end
  def create
    @category = StoreCategory.new(params[:store_category])
    @category.save
    redirect_to(root_store_categories_path)
  end
  def show
    #@categories  = StoreCategory.all
    @category = StoreCategory.find(params[:id])
    @subcategories = StoreCategory.where(:parent => @category.id)
  end
  def edit
    @category = StoreCategory.find(params[:id])
  end
  def update
    @category = StoreCategory.find(params[:id])
    @category.update_attributes(params[:store_category])
    redirect_to(root_store_category_path(@category))
  end
  def destroy
    @category = StoreCategory.find(params[:id])
    @category.destroy
    redirect_to(root_store_categories_path)
  end
end

app/controllers/root/users_controller.rb
class Root::UsersController < Root::ApplicationController
  
  def index
    @users = PlazrAuth::User.all
  end

  def show
    @user = PlazrAuth::User.find(params[:id])
    @roles = PlazrAuth::Role.all - @user.roles
  end

  def edit
    @user = PlazrAuth::User.find(params[:id])
  end

  def update
    @user = PlazrAuth::User.find(params[:id])
    @user.update_attributes(params[:user])
    redirect_to(root_user_path(@user))
  end

  def destroy
    @user = PlazrAuth::User.find(params[:id])
    @user.destroy
    redirect_to root_users_path
  end

  def addrole
    @user = PlazrAuth::User.find(params[:user_id])
    @role = PlazrAuth::Role.find(params[:role_id])
    @user.roles.push(@role) if (@user && @role)
    redirect_to(root_user_path(@user))
  end

  def rmrole
    @user = PlazrAuth::User.find(params[:user_id])
    @role = PlazrAuth::Role.find(params[:role_id])
    @user.roles.delete(@role) if (@user && @role)
    redirect_to(root_user_path(@user))
  end

end

app/views/root/users/edit.html.erb
<h1>Edit User</h1>

<%= form_for [:root,@user] do |u| %>
	<ul>
	<% @user.errors.full_messages.each do |error| %>
		<li><%= error %></li>
	<% end %>
	</ul>
	<p>
		<%= u.label :first_name %><br>
		<%= u.text_field :first_name %>
	</p>
	<p>
		<%= u.label :email %><br>
		<%= u.text_field :email %>
	</p>
	<p>
		<%= u.submit %>
	</p>
<% end %>

app/views/root/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.first_name %>
      <%= user.email %>
      <%= link_to 'Show', root_user_path(user) %>
      <%= link_to 'Edit', edit_root_user_path(user) %>
      <%= link_to "Delete", root_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

<%= link_to "Back to Home", plazrrs_path %>

app/views/root/users/show.html.erb
<h1>User: <%= @user.first_name %><%= @user.last_name %> </h1>

<p>Email : <%= @user.email %></p>

<p>
	<%= link_to "Edit", edit_root_user_path(@user) %>
	<%= link_to "Delete", root_user_path(@user), method: :delete , data: { confirm: 'Are you sure?' }%>
</p>

<h2>Roles</h2>
	<ul>
	<% @user.roles.each do |r| %>
		<li>
			<%= r.name %>
			<%= link_to "Delete" , root_rem_role_path(:user_id => @user.id, :role_id => r.id)%>
		</li>
	<% end %>
	<br>
	<% if(@roles.count>0) %>
		<%= form_tag root_add_role_path(:user_id => @user.id),:method => 'get' do %>
			<%= select_tag :role_id, options_for_select(@roles.map{|a| [a.name,a.id]}) %>
			<%= submit_tag 'Add Role' %>
		<% end %>
	<% end %>

</ul>
<br>

<%= link_to "Back to Users", root_users_path %>